# Generated by Django 5.0.3 on 2024-04-02 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assunto', models.IntegerField(choices=[(1, 'Reclamação'), (2, 'Dúvidas'), (3, 'Critica'), (4, 'Ajuda'), (5, 'Outro')])),
                ('nome', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('mensagem', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('subtitulo', models.CharField(max_length=300)),
                ('criador', models.CharField(max_length=200)),
                ('datatime_da_pub', models.DateTimeField(auto_now=True)),
                ('conteudo', models.TextField()),
                ('imagem', models.ImageField(upload_to='noticias/')),
            ],
        ),
    ]
