# Generated by Django 5.0.3 on 2024-04-03 00:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
