# Generated by Django 5.0.3 on 2024-03-30 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='imagem',
            field=models.ImageField(upload_to='cursos/'),
        ),
    ]
