# Generated by Django 5.0.3 on 2024-04-01 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0002_alter_curso_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('status', models.IntegerField(choices=[(1, 'formado'), (2, 'cursando')])),
                ('data_entrada', models.DateField()),
                ('data_saida', models.DateField(null=True)),
                ('imagem', models.ImageField(upload_to='cursos/alunos/')),
                ('curso', models.ManyToManyField(to='curso.curso')),
            ],
        ),
    ]
