# Generated by Django 5.0.3 on 2024-04-01 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0004_professor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='data_saida',
            field=models.DateField(blank=True, null=True),
        ),
    ]
